### ISSUE TITLE
LSM.keys() returning nonsense

### ISSUE THREAD

**Issue by hakonmh** [mosquito/python-lsm#1]
LSM.keys() doesn't return the right values: 
`[key for key in self.db.keys()]` 
-> `[b'has_def', b'index_column_posi', b'index_dtypen_position', b'index_namee', b'num_column', b'num_partiti', b'num_rowsitions', b'partitio', b'partitionsbyte_size', b'rows_per_p', b'rows_per_partition']`

Fetching keys by using LSM.items() returns the expected result:
`[key for key, _ in self.db.items()]` 
-> `[b'columns', b'has_default_index', b'index_column_position', b'index_dtype', b'index_name', b'num_columns', b'num_partitions', b'num_rows', b'partition_byte_size', b'partitions', b'rows_per_partition']`

Have tested using binary=True and binary=False in the LSM constructor and by inserting data using both LSM.update() and LSM[key]=value, the results of calling self.db.keys() is the same.

**Comment by mosquito** [comment]
I'm sorry you encountered a problem, but you should add details about your environment and the way you can reproduce the problem. I'm afraid I won't be able to help without it.

**Comment by hakonmh** [comment]
Here is a short snippet reproducing the bug:
```
from lsm import LSM

input_dict = {
    'c1': '',
    'c2': '',
    'c3': '',
    'c4': '',
    'c5': '',
}

db = LSM('test-db.lsm', binary=False)
db.open()
db.update(input_dict)
db.flush()
keys = [key for key in db.keys()]
```
Returns: `['c2', 'c3', 'c4', 'c5', 'c5']`

The problem seems to be with `db.flush()`, commenting out that line produces the correct result.

**Comment by mosquito** [comment]
@hakonmh it seems that something is missing to reproduce this behavior.

```
$ cat test.py
from lsm import LSM

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("--flush", action="store_true")

arguments = parser.parse_args()
print("Flush is", arguments.flush)

input_dict = {
    b'c1': b'',
    b'c2': b'',
    b'c3': b'',
    b'c4': b'',
    b'c5': b'',
}

db = LSM('test-db.lsm', binary=True)
db.open()
db.update(input_dict)

if arguments.flush:
    db.flush()

keys = [key for key in db.keys()]
print(keys)
$ python test.py
Flush is False
[b'c1', b'c2', b'c3', b'c4', b'c5']
$ python test.py --flush
Flush is True
[b'c2', b'c3', b'c4', b'c5', b'c5']
```

Could you please provide an instance of a buggy database?

**Comment by hakonmh** [comment]
Here is the database shown in the original example:
[table-metadata.tar.gz](https://github.com/mosquito/python-lsm/files/7546324/table-metadata.tar.gz)

**Comment by hakonmh** [comment]
Works correctly with the latest hotfix
